name: RedstoneCommandSigns
main: pgDev.bukkit.RedstoneCommandSigns.RCSMain
version: 0.1
author: PG Dev Team
authors: [Devil Boy]
description: Redstone has taken command!
depend: [SimpleCommandSigns]
softdepend: [HiddenCommandSigns]

commands:
   redstonecommandsigns:
      description: Main command.
      usage: /<command>
   rcs:
      description: Alt command.
      usage: /<command>

permissions:
    rcs.*:
        default: op
        description: Gives access to all Redstone Command Signs usage.
        children:
            rcs.create: true
    rcs.create:
        default: op
        description: Can create a redstone command sign.